In [1]:
import pandas as pd
import payments_manager as pm
df_jo = pm.df('df_jo')
pd.options.display.max_columns = None
display(df_jo.sort_values(['created_at','created_at_fe']).head(5))

,id_cr,id_fe,fe_cr_id,user_id,active,created_at,created_at_fe,amount,fee,stat_cr,stat_fe,transfer_type,type,to_receive_ini,to_receive_bank,to_reimbur,to_reimbur_cash,to_end,to_send,send_at,cr_received_date,money_back_date,reimbursement_date,paid_at,charge_moment,moderated_at,reason,category,from_date,to_date,recovery_status,updated_at,reco_creation,reco_last_update,updated_at_fe,Mes_created_at,cash_request_received_date,created_at_slot,created_at_slot_h,created_at_dow,needs_m_check,needs_m_check_recov,n_fees,n_backs,n_recovery,n_incidents,created_at_d,GBP_EUR,BTC_GBP,inflation,unemploy_rate
0,3,0,NaN,47,1,2019-11-19 13:57:53.511561,NaT,1.0,0.0,canceled,cr_regular,regular,nice,NaT,NaT,16 days 09:02:06.488439,NaT,NaT,NaT,NaT,NaT,NaT,2019-12-05 23:00:00.000000,NaT,NaN,2019-11-20 12:16:50.000000,NaN,NaN,NaT,NaT,nice,2020-12-14 10:25:57.710844,NaT,NaT,NaT,2019-11,NaT,7,13-Ma√±ana,1,1,1,0,0,0,1,2019-11-19,1.16935,6347.577148,1.3,4.0
1,4,0,NaN,99001309,0,2019-12-09 14:47:35.190714,NaT,100.0,0.0,money_back,cr_regular,regular,nice,NaT,NaT,7 days 08:12:24.809286,NaT,0 days,NaT,NaT,NaT,2019-12-16 23:00:00,2019-12-16 23:00:00.000000,NaT,NaN,2019-12-09 14:58:28.000000,NaN,NaN,NaT,NaT,nice,2020-11-04 12:54:52.120014,NaT,NaT,NaT,2019-12,NaT,14,14-Tarde,0,0,0,0,1,0,0,2019-12-09,1.18803,5630.115723,1.3,4.0
2,5,0,NaN,804,1,2019-12-10 19:05:21.596873,NaT,100.0,0.0,rejected,cr_regular,regular,nice,NaT,NaT,29 days 23:59:59.999490,NaT,NaT,NaT,NaT,NaT,NaT,2020-01-09 19:05:21.596363,NaT,NaN,2019-12-11 16:47:42.405646,NaN,NaN,NaT,NaT,nice,2019-12-11 16:47:42.407830,NaT,NaT,NaT,2019-12,NaT,14,19-Tarde,1,1,1,0,0,0,1,2019-12-10,1.18800,5543.707520,1.3,4.0
3,6,0,NaN,812,1,2019-12-10 19:05:48.921042,NaT,100.0,0.0,direct_debit_rejected,cr_regular,regular,nice,0 days 04:54:11.078958,NaT,57 days 03:54:11.078958,NaT,NaT,NaT,NaT,2019-12-11,NaT,2020-02-05 23:00:00.000000,NaT,NaN,2019-12-11 09:40:33.000000,NaN,NaN,NaT,NaT,pending,2020-12-18 22:47:47.993817,2020-03-20 14:12:53.208246,2020-12-18 22:47:48.008850,NaT,2019-12,2019-12-11,14,19-Tarde,1,1,1,0,0,1,1,2019-12-10,1.18800,5543.707520,1.3,4.0
4,7,0,NaN,191,1,2019-12-10 19:13:35.825460,NaT,100.0,0.0,rejected,cr_regular,regular,nice,NaT,NaT,29 days 23:59:59.999581,NaT,NaT,NaT,NaT,NaT,NaT,2020-01-09 19:13:35.825041,NaT,NaN,2019-12-11 09:46:59.777728,NaN,NaN,NaT,NaT,nice,2019-12-11 09:46:59.779773,NaT,NaT,NaT,2019-12,NaT,14,19-Tarde,1,1,1,0,0,0,1,2019-12-10,1.18800,5543.707520,1.3,4.0